### ISSUE TITLE
get rid of Cash and use BigDecimal instead

### ISSUE THREAD

**Issue by yegor256** [jcabi/jcabi-odesk#1]
Let's get rid of Cash and use BigDecimal instead

**Comment by cyberone** [comment]
@dmarkov please review https://github.com/jcabi/jcabi-odesk/pull/6

**Comment by cyberone** [comment]
@yegor256 the PR is merged and closed. Close the issue please.

**Comment by yegor256** [comment]
thanks!

**Comment by yegor256** [comment]
@rultor release, tag is `0.8`

**Comment by dmarkov** [comment]
@cyberone I just added **30 mins** to your account, many thanks for your contribution..... +30 added to your rating, current score is: [+20](http://www.netbout.com/b/35076?open=rating)
